MARP-616-A-Trust-Refactoring
axonivy-market/a-trust-connector pull request #38
Opened 2024-08-22 10:30 UTC by nqhoan-axonivy

2024-08-23 08:22 UTC, ivy-rew commented on a-trust-connector/src/resources/config/ATrust-OpenAPI.yaml
this is absolutely great, that you craft the openAPI for a-trust, this increases the maintainability of this service a lot :heart:

2024-08-23 08:24 UTC, ivy-rew reviewed
You completely had to switch the stack form SOAP to REST.
Now I do not see any tests that use mocks of the service payloads going to an fro.
Just like in the previous version it tests against live instances. We should avoid this and use a mock like in all other REST connectors. This will help us a lot:
- presales can show a demo when the service is not reachable or they are being offline
- we have documentation how the service worked in the past; if the service changes.

You may copy the 'mocking' approach from another connector or our examples: https://github.com/axonivy/project-build-examples/tree/master/compile-test/crmTests/src/ch/ivyteam/crm/mocks

2024-08-27 01:32 UTC, phhung-axonivy requested changes

2024-08-27 01:32 UTC, phhung-axonivy commented on a-trust-connector-product/README_DE.md
> +Für die Nutzung von A-Trust benötigst Du einen Account, den Dir https://www.a-trust.at/de/produkte/qualifizierte_signaturservices/xidentity/ erstellt.
It does not match the English version.

2024-08-27 01:32 UTC, phhung-axonivy commented on a-trust-connector/processes/ATrust/StartSignature.p.json
> +            "  in.forwardTargetUrl = in.forwardTargetUrl + ATrustService.generateIFrameParameters(450, 450, \"\", 0);",
Why do you use the fixed value 450?

2024-08-27 01:32 UTC, phhung-axonivy commented on a-trust-connector/src/com/axonivy/connector/atrust/constant/Constants.java
> +	public static final String TEMPLATE_DISPLAYNAME_PATTERN = "%s (#%d)";
`TEMPLATE_DISPLAYNAME_PATTERN` -> `TEMPLATE_DISPLAY_NAME_PATTERN `

2024-08-27 11:11 UTC, nqhoan-axonivy commented
Thank @ivy-rew so much for your hints!
I'm working on it now. Just make everything back to work, now I will create a mock service for testing.

2024-08-29 07:49 UTC, phhung-axonivy approved these changes
LGTM

2024-08-30 02:43 UTC, merged